/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Platform, StyleSheet, Text, View} from 'react-native';
import ReactNativeDeviceRisk from 'react-native-device-risk';

export default class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--',
    bb: '',
  };
  componentDidMount() {
    ReactNativeDeviceRisk.sampleMethod('Testing', 123, message => {
      this.setState({
        status: 'native callback received',
        message,
      });
    });

    ReactNativeDeviceRisk.blackbox().then((bb: string) => {
      this.setState({
        bb,
      });
    });
  }
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆ReactNativeDeviceRisk example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
        <Text style={styles.welcome}>☆NATIVE CALLBACK MESSAGE☆</Text>
        <Text style={styles.instructions}>{this.state.message}</Text>
        <Text style={styles.welcome}>BB</Text>
        <Text style={styles.instructions}>{this.state.bb}</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
